// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7ig7pI3_76io09yq2lwoCEFh73TtD3A',
    appId: '1:125357790545:web:5bd51d5f976d1189a16f70',
    messagingSenderId: '125357790545',
    projectId: 'kingmaker-2022',
    authDomain: 'kingmaker-2022.firebaseapp.com',
    databaseURL: 'https://kingmaker-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kingmaker-2022.appspot.com',
    measurementId: 'G-66B02EHE4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuK1BxhOnKZ8g4bX7Tc4_jDNfpbC2ZEo',
    appId: '1:125357790545:android:f4c25447cbe6b624a16f70',
    messagingSenderId: '125357790545',
    projectId: 'kingmaker-2022',
    databaseURL: 'https://kingmaker-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kingmaker-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqu2Pm8GCtWz40AgAiVtycEcCy44-arM',
    appId: '1:125357790545:ios:d77e52985584ddf6a16f70',
    messagingSenderId: '125357790545',
    projectId: 'kingmaker-2022',
    databaseURL: 'https://kingmaker-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kingmaker-2022.appspot.com',
    androidClientId: '125357790545-4j94pqdqpf84kdh83r05v6tfk4q4f1pr.apps.googleusercontent.com',
    iosClientId: '125357790545-oj8ae55sn8t1j94en2i5244odkek133i.apps.googleusercontent.com',
    iosBundleId: 'com.icyindia.kingmaker',
  );
}
